CREATE TYPE "PlatformRole" AS ENUM ('USER', 'ADMIN');
CREATE TYPE "GroupKind" AS ENUM ('CASUAL', 'OFFICIAL_CLUB');
CREATE TYPE "GroupRole" AS ENUM ('OWNER', 'ADMIN', 'OFFICER', 'MEMBER');
CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'REMOVED', 'LEFT', 'BLOCKED');
CREATE TYPE "ClubApplicationStatus" AS ENUM ('PENDING', 'CHANGES_REQUESTED', 'APPROVED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE "ClubMembershipApplicationStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN');
CREATE TYPE "AnnouncementVisibility" AS ENUM ('PUBLIC', 'MEMBERS');

ALTER TABLE "user" ADD COLUMN "platformRole" "PlatformRole" NOT NULL DEFAULT 'USER';
ALTER TABLE "group" ADD COLUMN "kind" "GroupKind" NOT NULL DEFAULT 'CASUAL', ADD COLUMN "universityId" TEXT, ADD COLUMN "slug" TEXT, ADD COLUMN "description" TEXT, ADD COLUMN "contactEmail" TEXT, ADD COLUMN "websiteUrl" TEXT, ADD COLUMN "discordUrl" TEXT, ADD COLUMN "githubUrl" TEXT, ADD COLUMN "logoUrl" TEXT, ADD COLUMN "approvedAt" TIMESTAMP(3), ADD COLUMN "approvedById" TEXT, ADD COLUMN "suspendedAt" TIMESTAMP(3), ADD COLUMN "suspensionReason" TEXT;
ALTER TABLE "group_membership" ADD COLUMN "role" "GroupRole" NOT NULL DEFAULT 'MEMBER', ADD COLUMN "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE', ADD COLUMN "publicOfficerVisible" BOOLEAN NOT NULL DEFAULT true, ADD COLUMN "endedAt" TIMESTAMP(3), ADD COLUMN "removedById" TEXT, ADD COLUMN "removalReason" TEXT;
UPDATE "group_membership" gm SET "role" = 'OWNER' FROM "group" g WHERE gm."groupId" = g.id AND gm."userId" = g."ownerId";
CREATE UNIQUE INDEX "group_slug_key" ON "group"("slug");
ALTER TABLE "group" ADD CONSTRAINT "group_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "university"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "club_application" ("id" TEXT PRIMARY KEY, "groupId" TEXT NOT NULL, "submittedById" TEXT NOT NULL, "universityId" TEXT NOT NULL, "status" "ClubApplicationStatus" NOT NULL DEFAULT 'PENDING', "proposedName" TEXT NOT NULL, "requestedSlug" TEXT NOT NULL, "description" TEXT NOT NULL, "officialWebsiteUrl" TEXT NOT NULL, "facultyAdvisorName" TEXT NOT NULL, "facultyAdvisorEmail" TEXT NOT NULL, "contactEmail" TEXT NOT NULL, "githubUrl" TEXT, "discordUrl" TEXT, "evidenceNote" TEXT NOT NULL, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedAt" TIMESTAMP(3), "reviewedById" TEXT, "reviewNote" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "club_application_groupId_status_idx" ON "club_application"("groupId", "status"); CREATE INDEX "club_application_status_submittedAt_idx" ON "club_application"("status", "submittedAt"); CREATE INDEX "club_application_requestedSlug_idx" ON "club_application"("requestedSlug");
ALTER TABLE "club_application" ADD CONSTRAINT "club_application_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "club_application" ADD CONSTRAINT "club_application_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "club_application" ADD CONSTRAINT "club_application_universityId_fkey" FOREIGN KEY ("universityId") REFERENCES "university"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "club_application" ADD CONSTRAINT "club_application_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "club_membership_application" ("id" TEXT PRIMARY KEY, "groupId" TEXT NOT NULL, "userId" TEXT NOT NULL, "status" "ClubMembershipApplicationStatus" NOT NULL DEFAULT 'PENDING', "message" TEXT, "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedAt" TIMESTAMP(3), "reviewedById" TEXT, "reviewNote" TEXT, "withdrawnAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "club_membership_application_groupId_status_submittedAt_idx" ON "club_membership_application"("groupId", "status", "submittedAt"); CREATE INDEX "club_membership_application_userId_groupId_submittedAt_idx" ON "club_membership_application"("userId", "groupId", "submittedAt");
ALTER TABLE "club_membership_application" ADD CONSTRAINT "club_membership_application_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "club_membership_application" ADD CONSTRAINT "club_membership_application_userId_fkey" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "club_membership_application" ADD CONSTRAINT "club_membership_application_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "club_announcement" ("id" TEXT PRIMARY KEY, "groupId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "visibility" "AnnouncementVisibility" NOT NULL, "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "archivedAt" TIMESTAMP(3));
CREATE INDEX "club_announcement_groupId_visibility_publishedAt_idx" ON "club_announcement"("groupId", "visibility", "publishedAt"); ALTER TABLE "club_announcement" ADD CONSTRAINT "club_announcement_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "club_announcement" ADD CONSTRAINT "club_announcement_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "audit_event" ("id" TEXT PRIMARY KEY, "actorId" TEXT NOT NULL, "groupId" TEXT, "action" TEXT NOT NULL, "targetType" TEXT NOT NULL, "targetId" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "audit_event_groupId_createdAt_idx" ON "audit_event"("groupId", "createdAt"); CREATE INDEX "audit_event_actorId_createdAt_idx" ON "audit_event"("actorId", "createdAt"); ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "group"("id") ON DELETE SET NULL ON UPDATE CASCADE;
